language: ruby
sudo: false
cache: bundler
script:
  - bundle exec rake jetty:clean
  - bundle exec rake jetty:config
  - bundle exec rake jetty:start
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - for ORG in cctv wcvb wgbh whdh; do bundle exec rake data:$ORG file=spec/fixtures/xml/$ORG.pbcore.xml; done
  - bundle exec rspec
