require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShoppingCartItemsController do

  # This should return the minimal set of attributes required to create a valid
  # ShoppingCartItem. As you add validations to ShoppingCartItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all shopping_cart_items as @shopping_cart_items" do
      shopping_cart_item = ShoppingCartItem.create! valid_attributes
      get :index
      assigns(:shopping_cart_items).should eq([shopping_cart_item])
    end
  end

  describe "GET show" do
    it "assigns the requested shopping_cart_item as @shopping_cart_item" do
      shopping_cart_item = ShoppingCartItem.create! valid_attributes
      get :show, :id => shopping_cart_item.id.to_s
      assigns(:shopping_cart_item).should eq(shopping_cart_item)
    end
  end

  describe "GET new" do
    it "assigns a new shopping_cart_item as @shopping_cart_item" do
      get :new
      assigns(:shopping_cart_item).should be_a_new(ShoppingCartItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested shopping_cart_item as @shopping_cart_item" do
      shopping_cart_item = ShoppingCartItem.create! valid_attributes
      get :edit, :id => shopping_cart_item.id.to_s
      assigns(:shopping_cart_item).should eq(shopping_cart_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShoppingCartItem" do
        expect {
          post :create, :shopping_cart_item => valid_attributes
        }.to change(ShoppingCartItem, :count).by(1)
      end

      it "assigns a newly created shopping_cart_item as @shopping_cart_item" do
        post :create, :shopping_cart_item => valid_attributes
        assigns(:shopping_cart_item).should be_a(ShoppingCartItem)
        assigns(:shopping_cart_item).should be_persisted
      end

      it "redirects to the created shopping_cart_item" do
        post :create, :shopping_cart_item => valid_attributes
        response.should redirect_to(ShoppingCartItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shopping_cart_item as @shopping_cart_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCartItem.any_instance.stub(:save).and_return(false)
        post :create, :shopping_cart_item => {}
        assigns(:shopping_cart_item).should be_a_new(ShoppingCartItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCartItem.any_instance.stub(:save).and_return(false)
        post :create, :shopping_cart_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shopping_cart_item" do
        shopping_cart_item = ShoppingCartItem.create! valid_attributes
        # Assuming there are no other shopping_cart_items in the database, this
        # specifies that the ShoppingCartItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShoppingCartItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => shopping_cart_item.id, :shopping_cart_item => {'these' => 'params'}
      end

      it "assigns the requested shopping_cart_item as @shopping_cart_item" do
        shopping_cart_item = ShoppingCartItem.create! valid_attributes
        put :update, :id => shopping_cart_item.id, :shopping_cart_item => valid_attributes
        assigns(:shopping_cart_item).should eq(shopping_cart_item)
      end

      it "redirects to the shopping_cart_item" do
        shopping_cart_item = ShoppingCartItem.create! valid_attributes
        put :update, :id => shopping_cart_item.id, :shopping_cart_item => valid_attributes
        response.should redirect_to(shopping_cart_item)
      end
    end

    describe "with invalid params" do
      it "assigns the shopping_cart_item as @shopping_cart_item" do
        shopping_cart_item = ShoppingCartItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCartItem.any_instance.stub(:save).and_return(false)
        put :update, :id => shopping_cart_item.id.to_s, :shopping_cart_item => {}
        assigns(:shopping_cart_item).should eq(shopping_cart_item)
      end

      it "re-renders the 'edit' template" do
        shopping_cart_item = ShoppingCartItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCartItem.any_instance.stub(:save).and_return(false)
        put :update, :id => shopping_cart_item.id.to_s, :shopping_cart_item => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shopping_cart_item" do
      shopping_cart_item = ShoppingCartItem.create! valid_attributes
      expect {
        delete :destroy, :id => shopping_cart_item.id.to_s
      }.to change(ShoppingCartItem, :count).by(-1)
    end

    it "redirects to the shopping_cart_items list" do
      shopping_cart_item = ShoppingCartItem.create! valid_attributes
      delete :destroy, :id => shopping_cart_item.id.to_s
      response.should redirect_to(shopping_cart_items_url)
    end
  end

end
