require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShoppingCartsController do

  # This should return the minimal set of attributes required to create a valid
  # ShoppingCart. As you add validations to ShoppingCart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    pending "assigns all shopping_carts as @shopping_carts" do
      shopping_cart = ShoppingCart.create! valid_attributes
      get :index
      assigns(:shopping_carts).should eq([shopping_cart])
    end
  end

  describe "GET show" do
    pending "assigns the requested shopping_cart as @shopping_cart" do
      shopping_cart = ShoppingCart.create! valid_attributes
      get :show, :id => shopping_cart.id.to_s
      assigns(:shopping_cart).should eq(shopping_cart)
    end
  end

  describe "GET new" do
    pending "assigns a new shopping_cart as @shopping_cart" do
      get :new
      assigns(:shopping_cart).should be_a_new(ShoppingCart)
    end
  end

  describe "GET edit" do
    pending "assigns the requested shopping_cart as @shopping_cart" do
      shopping_cart = ShoppingCart.create! valid_attributes
      get :edit, :id => shopping_cart.id.to_s
      assigns(:shopping_cart).should eq(shopping_cart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      pending "creates a new ShoppingCart" do
        expect {
          post :create, :shopping_cart => valid_attributes
        }.to change(ShoppingCart, :count).by(1)
      end

      pending "assigns a newly created shopping_cart as @shopping_cart" do
        post :create, :shopping_cart => valid_attributes
        assigns(:shopping_cart).should be_a(ShoppingCart)
        assigns(:shopping_cart).should be_persisted
      end

      pending "redirects to the created shopping_cart" do
        post :create, :shopping_cart => valid_attributes
        response.should redirect_to(ShoppingCart.last)
      end
    end

    describe "with invalid params" do
      pending "assigns a newly created but unsaved shopping_cart as @shopping_cart" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCart.any_instance.stub(:save).and_return(false)
        post :create, :shopping_cart => {}
        assigns(:shopping_cart).should be_a_new(ShoppingCart)
      end

      pending "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCart.any_instance.stub(:save).and_return(false)
        post :create, :shopping_cart => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      pending "updates the requested shopping_cart" do
        shopping_cart = ShoppingCart.create! valid_attributes
        # Assuming there are no other shopping_carts in the database, this
        # specifies that the ShoppingCart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShoppingCart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => shopping_cart.id, :shopping_cart => {'these' => 'params'}
      end

      pending "assigns the requested shopping_cart as @shopping_cart" do
        shopping_cart = ShoppingCart.create! valid_attributes
        put :update, :id => shopping_cart.id, :shopping_cart => valid_attributes
        assigns(:shopping_cart).should eq(shopping_cart)
      end

      pending "redirects to the shopping_cart" do
        shopping_cart = ShoppingCart.create! valid_attributes
        put :update, :id => shopping_cart.id, :shopping_cart => valid_attributes
        response.should redirect_to(shopping_cart)
      end
    end

    describe "with invalid params" do
      pending "assigns the shopping_cart as @shopping_cart" do
        shopping_cart = ShoppingCart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCart.any_instance.stub(:save).and_return(false)
        put :update, :id => shopping_cart.id.to_s, :shopping_cart => {}
        assigns(:shopping_cart).should eq(shopping_cart)
      end

      pending "re-renders the 'edit' template" do
        shopping_cart = ShoppingCart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShoppingCart.any_instance.stub(:save).and_return(false)
        put :update, :id => shopping_cart.id.to_s, :shopping_cart => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    pending "destroys the requested shopping_cart" do
      shopping_cart = ShoppingCart.create! valid_attributes
      expect {
        delete :destroy, :id => shopping_cart.id.to_s
      }.to change(ShoppingCart, :count).by(-1)
    end

    pending "redirects to the shopping_carts list" do
      shopping_cart = ShoppingCart.create! valid_attributes
      delete :destroy, :id => shopping_cart.id.to_s
      response.should redirect_to(shopping_carts_url)
    end
  end

end
